apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: convertice
spec:
  schedule: "0 12 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: convertice
              volumeMounts:
                - name: gcp-credentials-volume
                  mountPath: /var/secrets/google
              image: bufferapp/convertice-job:0.2.0
              env:
                - name: GOOGLE_APPLICATION_CREDENTIALS
                  value: /var/secrets/google/key.json
              imagePullPolicy: Always
          imagePullSecrets:
            - name: dockerhub
          restartPolicy: OnFailure
          volumes:
            - name: gcp-credentials-volume
              secret:
                secretName: gcp-convertice
